CREATE TABLE `portfolio_config` (
	`id` int AUTO_INCREMENT NOT NULL,
	`aumBrl` double NOT NULL,
	`volTargetAnnual` double NOT NULL DEFAULT 0.1,
	`riskBudgetBrl` double NOT NULL,
	`baseCurrency` varchar(3) NOT NULL DEFAULT 'BRL',
	`enableFx` boolean NOT NULL DEFAULT true,
	`enableFront` boolean NOT NULL DEFAULT true,
	`enableBelly` boolean NOT NULL DEFAULT true,
	`enableLong` boolean NOT NULL DEFAULT true,
	`enableHard` boolean NOT NULL DEFAULT true,
	`fxInstrument` enum('DOL','WDO') NOT NULL DEFAULT 'WDO',
	`maxDrawdownPct` double NOT NULL DEFAULT -0.1,
	`maxLeverageGross` double NOT NULL DEFAULT 5,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `portfolio_config_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `portfolio_positions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`configId` int NOT NULL,
	`snapshotId` int,
	`instrument` enum('fx','front','belly','long','hard') NOT NULL,
	`b3Ticker` varchar(20) NOT NULL,
	`b3InstrumentType` varchar(20) NOT NULL,
	`direction` enum('long','short','flat') NOT NULL,
	`modelWeight` double NOT NULL,
	`riskAllocationBrl` double NOT NULL,
	`riskAllocationPct` double NOT NULL,
	`notionalBrl` double NOT NULL,
	`notionalUsd` double,
	`contracts` int NOT NULL,
	`contractSize` double NOT NULL,
	`dv01Brl` double,
	`fxDeltaBrl` double,
	`spreadDv01Usd` double,
	`entryPrice` double,
	`currentPrice` double,
	`unrealizedPnlBrl` double DEFAULT 0,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `portfolio_positions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `portfolio_snapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`configId` int NOT NULL,
	`modelRunId` int,
	`snapshotDate` varchar(10) NOT NULL,
	`snapshotType` enum('rebalance','daily_mtm','manual') NOT NULL,
	`aumBrl` double NOT NULL,
	`totalPnlBrl` double NOT NULL DEFAULT 0,
	`totalPnlPct` double NOT NULL DEFAULT 0,
	`overlayPnlBrl` double NOT NULL DEFAULT 0,
	`cdiPnlBrl` double NOT NULL DEFAULT 0,
	`portfolioVolAnnual` double,
	`varDaily95Brl` double,
	`varDaily99Brl` double,
	`currentDrawdownPct` double,
	`maxDrawdownPct` double,
	`grossExposureBrl` double,
	`netExposureBrl` double,
	`grossLeverage` double,
	`positionsJson` json,
	`riskDecompJson` json,
	`tradesJson` json,
	`exposureJson` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `portfolio_snapshots_id` PRIMARY KEY(`id`)
);
