CREATE TABLE `portfolio_alerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`configId` int NOT NULL,
	`alertType` enum('var_breach','drawdown_breach','margin_warning','regime_change','rebalance_due','model_update','position_limit','custom') NOT NULL,
	`severity` enum('info','warning','critical') NOT NULL DEFAULT 'info',
	`title` varchar(200) NOT NULL,
	`message` text NOT NULL,
	`metricValue` double,
	`thresholdValue` double,
	`isRead` boolean NOT NULL DEFAULT false,
	`isDismissed` boolean NOT NULL DEFAULT false,
	`notifiedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `portfolio_alerts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `portfolio_pnl_daily` (
	`id` int AUTO_INCREMENT NOT NULL,
	`configId` int NOT NULL,
	`pnlDate` varchar(10) NOT NULL,
	`totalPnlBrl` double NOT NULL DEFAULT 0,
	`overlayPnlBrl` double NOT NULL DEFAULT 0,
	`cdiPnlBrl` double NOT NULL DEFAULT 0,
	`fxPnlBrl` double DEFAULT 0,
	`frontPnlBrl` double DEFAULT 0,
	`bellyPnlBrl` double DEFAULT 0,
	`longPnlBrl` double DEFAULT 0,
	`hardPnlBrl` double DEFAULT 0,
	`cumulativePnlBrl` double NOT NULL DEFAULT 0,
	`cumulativePnlPct` double NOT NULL DEFAULT 0,
	`cdiDailyPnlBrl` double DEFAULT 0,
	`cumulativeCdiPnlBrl` double DEFAULT 0,
	`aumBrl` double NOT NULL,
	`drawdownPct` double DEFAULT 0,
	`hwmBrl` double,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `portfolio_pnl_daily_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `portfolio_trades` (
	`id` int AUTO_INCREMENT NOT NULL,
	`configId` int NOT NULL,
	`snapshotId` int,
	`instrument` enum('fx','front','belly','long','hard') NOT NULL,
	`b3Ticker` varchar(20) NOT NULL,
	`b3InstrumentType` varchar(20) NOT NULL,
	`tradeType` enum('model_recommended','manual_adjustment','stop_loss','take_profit','roll') NOT NULL DEFAULT 'model_recommended',
	`action` enum('BUY','SELL') NOT NULL,
	`contracts` int NOT NULL,
	`executedPrice` double NOT NULL,
	`targetPrice` double,
	`notionalBrl` double NOT NULL,
	`notionalUsd` double,
	`commissionBrl` double DEFAULT 0,
	`slippageBrl` double DEFAULT 0,
	`totalCostBrl` double DEFAULT 0,
	`currentPrice` double,
	`unrealizedPnlBrl` double DEFAULT 0,
	`realizedPnlBrl` double DEFAULT 0,
	`status` enum('pending','executed','partially_filled','cancelled') NOT NULL DEFAULT 'pending',
	`executedAt` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `portfolio_trades_id` PRIMARY KEY(`id`)
);
