CREATE TABLE `model_alerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`modelRunId` int,
	`alertType` enum('regime_change','shap_shift','score_change','drawdown_warning','model_degradation','data_quality') NOT NULL,
	`severity` enum('info','warning','critical') NOT NULL DEFAULT 'info',
	`title` varchar(200) NOT NULL,
	`message` text NOT NULL,
	`previousValue` varchar(100),
	`currentValue` varchar(100),
	`threshold` double,
	`instrument` varchar(20),
	`feature` varchar(100),
	`detailsJson` json,
	`isRead` boolean NOT NULL DEFAULT false,
	`isDismissed` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `model_alerts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `model_changelog` (
	`id` int AUTO_INCREMENT NOT NULL,
	`modelRunId` int,
	`version` varchar(20) NOT NULL,
	`runDate` varchar(10) NOT NULL,
	`score` double,
	`regime` varchar(30),
	`regimeCarryProb` double,
	`regimeRiskoffProb` double,
	`regimeStressProb` double,
	`backtestSharpe` double,
	`backtestReturn` double,
	`backtestMaxDD` double,
	`backtestWinRate` double,
	`backtestMonths` int,
	`weightFx` double,
	`weightFront` double,
	`weightBelly` double,
	`weightLong` double,
	`weightHard` double,
	`trainingWindow` int,
	`nStressScenarios` int,
	`changesJson` json,
	`metricsJson` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `model_changelog_id` PRIMARY KEY(`id`)
);
